#!/bin/bash

#############################################
# MS ABC Retailer Management System
# One-Click Install & Run (Docker)
#############################################

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

echo -e "${BLUE}"
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║     MS ABC Retailer Management System - Quick Start         ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo -e "${NC}"

#############################################
# Step 1: Check Docker is installed & running
#############################################
echo -e "${YELLOW}[1/5] Checking prerequisites...${NC}"

if ! command -v docker &> /dev/null; then
    echo -e "${RED}Docker is not installed.${NC}"
    echo "  Install it from: https://www.docker.com/products/docker-desktop/"
    exit 1
fi
echo -e "${GREEN}  ✓ Docker $(docker --version | grep -oP '\d+\.\d+\.\d+')${NC}"

# Check if docker compose is available (v2 plugin or standalone)
if docker compose version &> /dev/null; then
    COMPOSE_CMD="docker compose"
elif command -v docker-compose &> /dev/null; then
    COMPOSE_CMD="docker-compose"
else
    echo -e "${RED}Docker Compose is not installed.${NC}"
    echo "  Install Docker Desktop which includes Compose, or install the plugin separately."
    exit 1
fi
echo -e "${GREEN}  ✓ Docker Compose available${NC}"

# Check Docker daemon is running
if ! docker info &> /dev/null 2>&1; then
    echo -e "${RED}Docker is installed but not running.${NC}"
    echo "  Please start Docker Desktop and try again."
    exit 1
fi
echo -e "${GREEN}  ✓ Docker is running${NC}"

#############################################
# Step 2: Create required directories
#############################################
echo -e "${YELLOW}[2/5] Setting up directories...${NC}"

mkdir -p backups logs generated-forms
echo -e "${GREEN}  ✓ Directories ready${NC}"

#############################################
# Step 3: Create .env if it doesn't exist
#############################################
echo -e "${YELLOW}[3/5] Configuring environment...${NC}"

if [ ! -f ".env" ]; then
    # Generate a random password
    DB_PASS=$(openssl rand -base64 24 | tr -dc 'a-zA-Z0-9' | head -c 20 2>/dev/null || echo "msabc_secure_pass_42")

    cat > ".env" << EOF
# Generated by run.sh on $(date)
POSTGRES_USER=msabc
POSTGRES_PASSWORD=${DB_PASS}
POSTGRES_DB=ms_abc_db
POSTGRES_PORT=5433
REDIS_PORT=6380
BACKEND_PORT=3001
FRONTEND_PORT=3000
SYNC_ENABLED=true
SYNC_INTERVAL=daily
EOF
    echo -e "${GREEN}  ✓ Created .env with secure password${NC}"
else
    echo -e "${GREEN}  ✓ .env already exists${NC}"
fi

#############################################
# Step 4: Build and start all containers
#############################################
echo -e "${YELLOW}[4/5] Building and starting containers (this may take a few minutes on first run)...${NC}"

$COMPOSE_CMD up -d --build 2>&1 | while IFS= read -r line; do
    echo "  $line"
done

echo -e "${GREEN}  ✓ Containers started${NC}"

#############################################
# Step 5: Wait for services and seed database
#############################################
echo -e "${YELLOW}[5/5] Waiting for services to be ready...${NC}"

# Wait for PostgreSQL
echo -n "  Waiting for database"
for i in {1..30}; do
    if docker exec ms-abc-db pg_isready -U msabc -d ms_abc_db &> /dev/null; then
        echo ""
        echo -e "${GREEN}  ✓ Database is ready${NC}"
        break
    fi
    echo -n "."
    sleep 2
done

# Wait for backend
echo -n "  Waiting for backend API"
for i in {1..30}; do
    if curl -sf http://localhost:${BACKEND_PORT:-3001}/api/health &> /dev/null; then
        echo ""
        echo -e "${GREEN}  ✓ Backend API is ready${NC}"
        break
    fi
    echo -n "."
    sleep 2
done

# Seed the database (safe to re-run — uses upsert)
echo "  Seeding database..."
docker exec ms-abc-backend sh -c "cd /app/packages/backend && npx tsx prisma/seed.ts" 2>/dev/null || true
echo -e "${GREEN}  ✓ Database seeded${NC}"

# Wait for frontend
echo -n "  Waiting for frontend"
for i in {1..15}; do
    if curl -sf http://localhost:${FRONTEND_PORT:-3000} &> /dev/null; then
        echo ""
        echo -e "${GREEN}  ✓ Frontend is ready${NC}"
        break
    fi
    echo -n "."
    sleep 2
done

#############################################
# Done!
#############################################
echo ""
echo -e "${GREEN}╔══════════════════════════════════════════════════════════════╗"
echo -e "║                    Setup Complete!                            ║"
echo -e "╚══════════════════════════════════════════════════════════════╝${NC}"
echo ""
echo -e "  Open in your browser:"
echo ""
echo -e "  ${BLUE}App:${NC}          http://localhost:${FRONTEND_PORT:-3000}"
echo -e "  ${BLUE}Backend API:${NC}  http://localhost:${BACKEND_PORT:-3001}"
echo -e "  ${BLUE}Health:${NC}       http://localhost:${BACKEND_PORT:-3001}/api/health"
echo ""
echo -e "  ${YELLOW}Useful commands:${NC}"
echo "    $COMPOSE_CMD logs -f          # View live logs"
echo "    $COMPOSE_CMD ps               # Check service status"
echo "    $COMPOSE_CMD down             # Stop everything"
echo "    $COMPOSE_CMD up -d            # Start again"
echo "    ./manage.sh status            # Quick status check"
echo ""
